### ISSUE TITLE
Error handling on upload

### ISSUE THREAD

**Issue by andjo** [poppa/Roxen-Application-Launcher#8]
Just had the server return a 401 response when uploading an edited file, but the applauncher didn't seem to care and reported that the upload went fine.

**Comment by poppa** [comment]
Cool! Can you give an example of how to reproduce the 401? For some reason the `RoxenACauth` cookie must have been renewed on the server I guess?

**Comment by andjo** [comment]
Just temporarily cut permissions in AC and you have a test case.

**Comment by poppa** [comment]
Fixed!
